# Generated by Django 2.1.7 on 2019-04-11 16:34

import article.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=2048)),
                ('html', models.TextField()),
                ('cover_image', models.ImageField(height_field='cover_image_height', upload_to='article/static/media/', width_field='cover_image_width')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cover_image_height', models.IntegerField()),
                ('cover_image_width', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('is_email_validated', models.BooleanField(default=False)),
                ('picture', models.ImageField(default=article.models.default_image, height_field='picture_height', upload_to='article/static/media', width_field='picture_width')),
                ('picture_height', models.IntegerField()),
                ('picture_width', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ReadingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=2048)),
                ('articles', models.ManyToManyField(blank=True, to='article.Article')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Author'),
        ),
        migrations.AddField(
            model_name='article',
            name='reading_lists',
            field=models.ManyToManyField(blank=True, to='article.ReadingList'),
        ),
    ]
