# Generated by Django 2.1.7 on 2019-04-15 23:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20190415_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='email_validation_token',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
