# Generated by Django 2.1.7 on 2019-05-11 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_author_email_validation_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='cover_image_height',
        ),
        migrations.RemoveField(
            model_name='article',
            name='cover_image_width',
        ),
        migrations.AddField(
            model_name='article',
            name='cover_image_thumbnail',
            field=models.ImageField(default=1, height_field='thumbnail_height', upload_to='article/static/media/', width_field='thumbnail_width'),
            preserve_default=False,
        ),
    ]
