# Generated by Django 2.1.7 on 2019-05-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_misc_adjustments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cover_image',
            field=models.ImageField(upload_to='article/static/media/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='cover_image_thumbnail',
            field=models.ImageField(upload_to='article/static/media/'),
        ),
    ]
