# Generated by Django 2.1.7 on 2019-04-11 16:35

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configurable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welcome_title', models.CharField(max_length=512)),
                ('welcome_text', models.CharField(max_length=2048)),
                ('welcome_image', models.ImageField(upload_to='home/static/media')),
            ],
            managers=[
                ('single', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=2048)),
                ('quote', models.CharField(max_length=1024)),
                ('quoter', models.CharField(max_length=256)),
                ('image', models.ImageField(upload_to='home/static/media')),
                ('interval', models.PositiveIntegerField()),
            ],
            managers=[
                ('single', django.db.models.manager.Manager()),
            ],
        ),
    ]
