# Generated by Django 2.1.7 on 2019-03-31 22:25
import os

from django.conf import settings
from django.core.files.images import ImageFile
from django.db import migrations


def create_welcome_data(apps, schema_editor):
    """
    Creates a default Configurable instance to display welcome
    data to the web site
    """
    default_welcome_title = 'Welcome to Narrow Gate'
    default_welcome_text = (
        'Life is wasted if we do not grasp the glory '
        'of the cross, cherish it for the treasure that '
        'it is, and cleave to it as the highest price of '
        'every pleasure and the deepest comfort in every '
        'pain. What was once foolishness to us—a crucified '
        'God—must become our wisdom and our power and our '
        'only boast in this world.'
    )

    image_path = os.path.join(
        settings.BASE_DIR, 'home', 'static', 'welcome.jpg')
    image_os_file = open(image_path, 'r+b')
    default_welcome_image = ImageFile(image_os_file)

    Configurable = apps.get_model('home', 'Configurable')
    configurable, created = Configurable.single.get_or_create(
        welcome_title=default_welcome_title,
        welcome_text=default_welcome_text,
    )
    if created:
        configurable.welcome_image = default_welcome_image
        configurable.save()

    image_path = os.path.join(
        settings.BASE_DIR, 'home', 'static', 'praying-man.jpg')
    image_os_file = open(image_path, 'r+b')
    default_quote_image = ImageFile(image_os_file)

    Quote = apps.get_model('home', 'Quote')
    quote, _ = Quote.single.get_or_create(
        comment='Find Strength in Christ',
        quote="""
            But he said to me, "My grace is sufficient for you,
            for my power is made perfect in weakness." Therefore
            I will boast all the more gladly about my weaknesses,
            so that Christ's power may rest on me. That is why,
            for Christ's sake, I delight in weaknesses, in insults,
            in hardships, in persecutions, in difficulties. For
            when I am weak, then I am strong.
        """,
        quoter='2 Corinthians 12:9-10',
        interval=7,
    )
    if created:
        quote.image = default_quote_image
        quote.save()


def delete_welcome_data(apps, schema_editor):
    Configurable = apps.get_model('home', 'Configurable')
    Configurable.single.first().delete()

    Quote = apps.get_model('home', 'Quote')
    Quote.single.first().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_welcome_data, reverse_code=delete_welcome_data)
    ]
